# -*- coding: utf-8 -*-
"""Task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRv_qcswJzEGOawMdceHFdJ-c5ezTNsg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/sample_data/AmazonSalesData.csv')
df.head()

df.describe()

df.rename(columns={'Total Revenue': 'Revenue'}, inplace=True)

df.isnull().sum()

revenue_by_region = df.groupby('Region')['Revenue'].sum().reset_index()
regions=revenue_by_region['Region']
total_revenue=revenue_by_region['Revenue']

fig=plt.figure(figsize=(8,4))
bars=plt.bar(regions, total_revenue, color='pink')
plt.xlabel('Region')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Region')
plt.xticks(rotation=45, ha='right')
plt.subplots_adjust(bottom=0.25)
plt.show()

fig=plt.figure(figsize=(8,4))
plt.hist(df['Revenue'], bins=20, color='pink', edgecolor='red')
plt.xlabel('Total Profit')
plt.ylabel('Frequency')
plt.title('Histogram of Total Profit')
plt.show()